force-app/main/default/objects/Contact_Badge_Definition__mdt/Contact_Badge_Definition__mdt.object-meta.xml
<CustomObject>
    <description>Define the the criteria for and the appearance and behavior of displayed badges in the Contact Badges component</description>
    <label>Contact Badge Definition</label>
    <pluralLabel>Contact Badge Definitions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact_Badge_Definition__mdt/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Determines the order in which badges of this type will appear. Lowest numbers appear first; null values appear last.</description>
    <inlineHelpText>Determines the order in which badges of this type will appear. Lowest numbers appear first; null values appear last.</inlineHelpText>
    <label>Sort Order</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContactBadgeDefinitionWrapper_Test.cls
@IsTest
private class ContactBadgeDefinitionWrapper_Test {
    
    @IsTest
    static void testWrapperSorting() {
        ContactBadgesService.isTestScenario = true;
        
        List<Contact_Badge_Definition__mdt> lstDefinitions = Contact_Badge_Definition__mdt.getAll().values();
        List<Contact_Badge_Definition__mdt> lstSortedDefinitions = new List<Contact_Badge_Definition__mdt>();
        Test.startTest();
        ContactBadgeDefinitionWrapper[] lstCBDWrapper = new List<ContactBadgeDefinitionWrapper>();
        for (Contact_Badge_Definition__mdt definition : lstDefinitions) {
            lstCBDWrapper.add( new ContactBadgeDefinitionWrapper(definition) );
        }
        lstCBDWrapper.sort();
        for (ContactBadgeDefinitionWrapper cbdWrapper : lstCBDWrapper) {
            lstSortedDefinitions.add( cbdWrapper.cbd );
        }
        Test.stopTest();
        // Verify re-ordering by sort order
        Decimal lastSortOrder = 0;
        for (Contact_Badge_Definition__mdt sortedDefinition : lstSortedDefinitions) {
            System.assert(sortedDefinition.Sort_Order__c == null || sortedDefinition.Sort_Order__c >= lastSortOrder, 'Incorrect sort order');
            lastSortOrder = sortedDefinition.Sort_Order__c == null ? lastSortOrder : sortedDefinition.Sort_Order__c;
        }
    }

}