force-app/main/default/objects/Contact_Badge_Definition__mdt/Contact_Badge_Definition__mdt.object-meta.xml
<CustomObject>
    <description>Define the the criteria for and the appearance and behavior of displayed badges in the Contact Badges component</description>
    <label>Contact Badge Definition</label>
    <pluralLabel>Contact Badge Definitions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact_Badge_Definition__mdt/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Determines the order in which badges of this type will appear. Lowest numbers appear first; null values appear last.</description>
    <inlineHelpText>Determines the order in which badges of this type will appear. Lowest numbers appear first; null values appear last.</inlineHelpText>
    <label>Sort Order</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContactBadgeDefinitionWrapper.cls
public class ContactBadgeDefinitionWrapper implements Comparable {

    public Contact_Badge_Definition__mdt cbd;

    public ContactBadgeDefinitionWrapper(Contact_Badge_Definition__mdt definition) {
        cbd = definition;
    }

    // Compare Contact Badge Definitions based on sort order
    public Integer compareTo(Object compareTo) {
        // Cast argument to ContactBadgeDefinitionWrapper
        ContactBadgeDefinitionWrapper compareToDefinition = (ContactBadgeDefinitionWrapper)compareTo;
        
        // The return value of 0 indicates that both elements are equal.
        Integer returnValue = 0;
        if (cbd.Sort_Order__c > compareToDefinition.cbd.Sort_Order__c) {
            // Set return value to a positive value.
            returnValue = 1;
        } else if (cbd.Sort_Order__c < compareToDefinition.cbd.Sort_Order__c) {
            // Set return value to a negative value.
            returnValue = -1;
        } else if ((cbd.Sort_Order__c == null) && (compareToDefinition.cbd.Sort_Order__c != null)){
            // nulls-last implementation
            returnValue = 1;
        } else if ((cbd.Sort_Order__c != null) && (compareToDefinition.cbd.Sort_Order__c == null)){
            // nulls-last implementation
            returnValue = -1;
        }
        return returnValue;
    }

}