force-app/main/default/objects/Contact_Badge_Definition__mdt/Contact_Badge_Definition__mdt.object-meta.xml
<CustomObject>
    <description>Define the the criteria for and the appearance and behavior of displayed badges in the Contact Badges component</description>
    <label>Contact Badge Definition</label>
    <pluralLabel>Contact Badge Definitions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact_Badge_Definition__mdt/fields/Additional_Detail_Fields__c.field-meta.xml
<CustomField>
    <fullName>Additional_Detail_Fields__c</fullName>
    <description>The fields to display when a user selects a badge</description>
    <inlineHelpText>Enter API field names, separated by commas, for any fields that should be displayed when a user selects a badge</inlineHelpText>
    <label>Additional Detail Fields</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Badge_Definition__mdt/fields/Alert__c.field-meta.xml
<CustomField>
    <fullName>Alert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, a pop-up alert will display to the user when the page loads</description>
    <inlineHelpText>If checked, a pop-up alert will display to the user when the page loads</inlineHelpText>
    <label>Alert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Badge_Definition__mdt/fields/Alert_Message__c.field-meta.xml
<CustomField>
    <fullName>Alert_Message__c</fullName>
    <description>When Alert is checked, this message displays in the pop-up window a page loads. Use {!My_Custom_Field__c} syntax to display merged values from the child object</description>
    <inlineHelpText>When Alert is checked, this message displays in the pop-up window a page loads. Use {!My_Custom_Field__c} syntax to display merged values from the child object</inlineHelpText>
    <label>Alert Message</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Badge_Definition__mdt/fields/Background_Color__c.field-meta.xml
<CustomField>
    <fullName>Background_Color__c</fullName>
    <description>Hexadecimal color code for the badge background</description>
    <inlineHelpText>Hexadecimal color code for the badge background</inlineHelpText>
    <label>Background Color</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Badge_Definition__mdt/fields/Child_Object__c.field-meta.xml
<CustomField>
    <fullName>Child_Object__c</fullName>
    <description>The API name of the SObject that the badge&apos;s source data is based on</description>
    <inlineHelpText>The API name of the SObject that the badge&apos;s source data is based on</inlineHelpText>
    <label>Child Object</label>
    <length>58</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Badge_Definition__mdt/fields/Filter_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Filter_Criteria__c</fullName>
    <description>The criteria to include in the WHERE clause of the SOQL query</description>
    <inlineHelpText>The criteria to include in the WHERE clause of the SOQL query</inlineHelpText>
    <label>Filter Criteria</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact_Badge_Definition__mdt/fields/Icon_Name__c.field-meta.xml
<CustomField>
    <fullName>Icon_Name__c</fullName>
    <description>Use a supported Lightning Design System icon name (e.g. standard:brand)</description>
    <inlineHelpText>Use a supported Lightning Design System icon name (e.g. standard:brand)</inlineHelpText>
    <label>Icon Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Badge_Definition__mdt/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Use {!My_Custom_Field__c} syntax to display merged values from the child object</description>
    <inlineHelpText>Use {!My_Custom_Field__c} syntax to display merged values from the child object</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Badge_Definition__mdt/fields/Label_Color__c.field-meta.xml
<CustomField>
    <fullName>Label_Color__c</fullName>
    <description>Hexidecimal color code for the label text and icon</description>
    <inlineHelpText>Hexidecimal color code for the label text and icon</inlineHelpText>
    <label>Label Color</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Badge_Definition__mdt/fields/Order_By__c.field-meta.xml
<CustomField>
    <fullName>Order_By__c</fullName>
    <description>Optionally, define order in which badges are displayed (e.g. LastModifiedDate DESC)</description>
    <inlineHelpText>Optionally, define order in which badges are displayed (e.g. LastModifiedDate DESC)</inlineHelpText>
    <label>Order By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Badge_Definition__mdt/fields/Parent_ID_Path__c.field-meta.xml
<CustomField>
    <fullName>Parent_ID_Path__c</fullName>
    <description>The API path to the parent Contact or Account ID from the child object</description>
    <inlineHelpText>The API path to the parent Contact or Account ID from the child object (e.g. ContactId,  AccountId, My_Custom_Contact_Lookup__c,  My_Custom_Contact_Lookup__r.AccountId)</inlineHelpText>
    <label>Parent ID Path</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Badge_Definition__mdt/fields/Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object__c</fullName>
    <description>Indicates whether the source data is related to the contact or the contact&apos;s account</description>
    <inlineHelpText>Indicates whether the source data is related to the contact or the contact&apos;s account</inlineHelpText>
    <label>Parent Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contact</fullName>
                <default>true</default>
                <label>Contact</label>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactBadgesHelper.cls
public with sharing class ContactBadgesHelper {
    
    /****************************************************
     * Constants
     ****************************************************/

    private static final String DEFAULT_BACKGROUND_COLOR = '#D3D3D3';
    private static final String DEFAULT_LABEL_COLOR = '#000000';
    private static final String DEFAULT_ICON_NAME = 'utility:info';
    private static final String BADGE_LABEL_TYPE_VALUE = 'Value';
    private static final String BADGE_LABEL_TYPE_FIELD_REFERENCE = 'Field Reference';
    private static final String MERGE_FIELD_REGEX = '\\{!.+?\\}';

    /****************************************************
     * Sorts and returns a provided list of definitions, based on
     *     the sort order defined in the custom metadata record
     * @param List<Contact_Badge_Definition__mdt> Unsorted list of
     *     definitions
     ****************************************************/

    public static List<Contact_Badge_Definition__mdt> sortContactBadgeDefinitions(
        List<Contact_Badge_Definition__mdt> lstDefinitions
    ) {
        List<Contact_Badge_Definition__mdt> lstSortedDefinitions = new List<Contact_Badge_Definition__mdt>();
        ContactBadgeDefinitionWrapper[] lstCBDWrapper = new List<ContactBadgeDefinitionWrapper>();
        for (Contact_Badge_Definition__mdt definition : lstDefinitions) {
            lstCBDWrapper.add( new ContactBadgeDefinitionWrapper(definition) );
        }
        lstCBDWrapper.sort();
        for (ContactBadgeDefinitionWrapper cbdWrapper : lstCBDWrapper) {
            lstSortedDefinitions.add( cbdWrapper.cbd );
        }
        return lstSortedDefinitions;
    }

    /****************************************************
     * Returns a soql query string, constructed from custom metadata properties
     * @param Contact_Badge_Definition__mdt The definition record
     *     to construct a query for
     ****************************************************/

    public static String getQueryFromDefinition(
        Contact_Badge_Definition__mdt definition
    ) {
        // SELECT
        String query = 'SELECT Id ';
        Set<String> setDetailFields = getFieldsForSelector(definition);
        for (String field : setDetailFields) {
            query += ', ' + String.escapeSingleQuotes(field) + ' ';
        }

        // FROM
        query += 'FROM ' + String.escapeSingleQuotes(definition.Child_Object__c) + ' ';

        // WHERE
        query += 'WHERE ' + definition.Parent_ID_Path__c + ' = :';
        query += definition.Parent_Object__c == 'Account' ? 'accountId ' : 'recordId ';
        if (!String.isBlank(definition.Filter_Criteria__c)) {
            query += 'AND ' + definition.Filter_Criteria__c + ' ';
        }

        // ORDER BY
        if (!String.isBlank(definition.Order_By__c)) {
            query += 'ORDER BY ' + definition.Order_By__c;
        }

        return query;
    }

    /****************************************************
     * Returns the badge label for a single definition
     * @param Contact_Badge_Definition__mdt The definition record
     *     to construct a query for
     * @param SObject The api name of the sObject type being queried
     ****************************************************/

    public static String getBadgeLabel(
        Contact_Badge_Definition__mdt definition, 
        SObject obj
    ) {
        String badgeLabel = definition.Label__c.contains('{!')
            ? replaceMergeFieldsWithValues(definition.Label__c, obj) 
            : definition.Label__c;
        return badgeLabel;
    }

    /****************************************************
     * Returns the badge alert message for a single definition
     * @param Contact_Badge_Definition__mdt The definition record
     *     to construct a query for
     * @param SObject The api name of the sObject type
     ****************************************************/
    
    public static String getBadgeAlertMessage(
        Contact_Badge_Definition__mdt definition, 
        SObject obj
    ) {
        String alertMessage;
        if (
            definition.Alert__c && 
            !String.isBlank(definition.Alert_Message__c) &&
            definition.Alert_Message__c.contains('{!')
        ) {
            alertMessage = replaceMergeFieldsWithValues(
                definition.Alert_Message__c, 
                obj
            );
        } else {
            alertMessage = definition.Alert_Message__c;
        }
        return alertMessage;
    }

    /****************************************************
     * Returns a string that can be referenced in an html style attribute
     *     to display the badge's defined background color (or default)
     * @param Contact_Badge_Definition__mdt The definition record
     *     to get the badge color for
     ****************************************************/

    public static String getBadgeColorStyle(
        Contact_Badge_Definition__mdt definition
    ) {
        String hexColor = definition.Background_Color__c != null ? '#' + definition.Background_Color__c : DEFAULT_BACKGROUND_COLOR;
        String badgeColorStyle = '--sds-c-badge-color-background:' + hexColor + ';';
        return badgeColorStyle;
    }

    /****************************************************
     * Returns a string that can be referenced in an html style attribute
     *     to display the badge's defined label color (or default)
     * @param Contact_Badge_Definition__mdt The definition record
     *     to get the label color for
     ****************************************************/

    public static String getBadgeLabelStyle(
        Contact_Badge_Definition__mdt definition
    ) {
        String labelHexColor = definition.Label_Color__c != null ? '#' + definition.Label_Color__c : DEFAULT_LABEL_COLOR;
        String badgeLabelStyle = '--sds-c-badge-text-color:' + labelHexColor + ';--slds-c-badge-icon-color-foreground:' + labelHexColor;
        return badgeLabelStyle;
    }

    /****************************************************
     * Returns the name of the icon to display for this badge
     * @param Contact_Badge_Definition__mdt The definition record
     *     to get the badge icon for
     ****************************************************/

    public static String getBadgeIconName(
        Contact_Badge_Definition__mdt definition
    ) {
        String iconName = !String.isBlank(definition.Icon_Name__c) ? definition.Icon_Name__c : DEFAULT_ICON_NAME;
        return iconName;
    }

    /****************************************************
     * Returns a set of strings with each of the field names to include
     *     in the SELECT statement of the query
     * @param Contact_Badge_Definition__mdt The definition record
     *     to get selector fields for
     ****************************************************/

    private static Set<String> getFieldsForSelector(
        Contact_Badge_Definition__mdt definition
    ) {
        Set<String> fieldsForSelector = new Set<String>();
        // If displaying a label with merge fields, add the fields to the query
        if (
            !String.isBlank(definition.Label__c) && 
            definition.Label__c.contains('{!')
        ) {
            fieldsForSelector.addAll(
                getMergeFieldsFromString(definition.Label__c)
            );
        }
        // If displaying an alert, check for merge fields to add to query
        if (
            definition.Alert__c && 
            !String.isBlank(definition.Alert_Message__c) &&
            definition.Alert_Message__c.contains('{!')
        ) {
            fieldsForSelector.addAll(
                getMergeFieldsFromString(definition.Alert_Message__c)
            );
        }
        // Add all additional fields for the modal
        if (!String.isBlank(definition.Additional_Detail_Fields__c)) {
            fieldsForSelector.addAll(definition.Additional_Detail_Fields__c.replaceAll('\\s+', '').split(','));
        } else {
            fieldsForSelector.add('Name');
        }
        return fieldsForSelector;
    }


    /****************************************************
     * Returns a set of strings with each of the merge fields
     *     contained in the original string
     * @param String String containing merge fields
     ****************************************************/

    private static Set<String> getMergeFieldsFromString(
        String input
    ) {
        Set<String> setMergeFields = new Set<String>();
        Pattern p = Pattern.compile(MERGE_FIELD_REGEX);
        Matcher m = p.matcher(input);
        while(m.find()) {
            String mergeFieldApiName = m.group().substring(
                2, 
                m.group().length() - 1
            );
            setMergeFields.add(mergeFieldApiName);
        }
        return setMergeFields;
    }

    /****************************************************
     * Returns the original string with merge fields substituted
     *     for their values
     * @param String String containing merge fields to be replaced
     * @param SObject The api name of the sObject type
     ****************************************************/

    private static String replaceMergeFieldsWithValues(
        String input,
        SObject obj
    ) {
        String result = input;
        Map<String,Object> mapObjFields = obj.getPopulatedFieldsAsMap();
        Pattern p = Pattern.compile(MERGE_FIELD_REGEX);
        Matcher m = p.matcher(result);
        while(m.find()) {
            String fieldApiName = m.group().substring(
                2, 
                m.group().length() - 1
            );
            result = String.valueOf(mapObjFields.get(fieldApiName)) != null ?
                result.replace(m.group(0), String.valueOf(mapObjFields.get(fieldApiName))) :
                result.replace(m.group(0), '');
        }
        return result;
    }


}